services:
  - type: web
    name: change-demo-system
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn wsgi:app"
    runtime: python3.11